export { courseTimetable } from './api/course-timetable';
export { moduleDetails } from './api/module-details';
export { moduleExamTimetable } from './api/module-exam-timetable';
export { moduleTimetable } from './api/module-timetable';
export { roomDetails } from './api/room-details';
export { roomTimetable } from './api/room-timetable';
export { studentExamTimetable } from './api/student-exam-timetable';
export { studentTimetable } from './api/student-timetable';
export { weekDates } from './api/week-dates';
